### ISSUE TITLE
NavigationView Components are not working when PodSlider is added as a dependency.

### ISSUE THREAD

**Issue by sandeeprapolu466** [bhargavms/PodSLider#10]
When adding PodSlider library dependency, NavigationView in my app are throwing null pointer exception.

**Comment by bhargavms** [comment]
This is not some magic library that does reflection on NavigationView class and alters its properties, this library does nothing with `NavigationView` , I don't understand how just including this library in your dependencies can actually break your NavigationView?

**Comment by bhargavms** [comment]
@sandeep466github  A stacktrace would be nice here !

**Comment by sandeep466github** [comment]
Actually... I am not even using the library.. just adding PodSlider as a dependency is crashing my code.
I guess there is some conflict with my support librarys. PodSlider might be using latest support libraries and my project support libraries doesnt match.

**Comment by bhargavms** [comment]
this is the only dependency I've added mainly for the support annotations
`compile 'com.android.support:appcompat-v7:23.4.0'`
Maybe I should remove that.

**Comment by bhargavms** [comment]
@sandeep466github this is the only dependency of the library 

`compile 'com.android.support:appcompat-v7:23.4.0'`

I use that mainly for the support annotations like `@colorRes` etc. And NavigationView is only available in the support design library so I dont understand how there's a conflict like you mention

**Comment by sandeep466github** [comment]
I got it.I am using the old version 23.0.1. As you are using support librarys version 23.4.0 ..When I updated the version to yours. There is a known bug in navigationView implementation . Anyhow I solved it. thanks.
:-)
